version: '3.8'

services:
  #Service 1: 你的 Python 执行环境 (基于你的 Dockerfile)
  agent-sandbox:
    build: .  # "." 表示使用当前目录下的 Dockerfile 构建
    container_name: python_agent_sandbox
    ports:
      - "5001:5000"  # We move the entrance to 5001
    volumes:
      - ./workspace:/app/workspace # 挂载工作区，方便存图
    environment:
      - DB_HOST=db  # 告诉 Python，数据库的主机名是 "db"
    depends_on:
      - db # 确保数据库先启动

  # Service 2: 数据库 (PostgreSQL)
  db:
    image: postgres:15-alpine
    container_name: banking_postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: banking_system
    ports:
      - "5432:5432" # 允许 Windows 主机 (Streamlit) 连接
    volumes:
      - pg_data:/var/lib/postgresql/data

  # Service 3: 数据库管理界面 (可选)
  pgadmin:
    image: dpage/pgadmin4
    container_name: banking_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@tarc.edu.my
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pg_data: